### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by tracend** [webcomponents/element-boilerplate#6]
Thanks for setting this up and your work with Web Components in general. 

May I ask if you can consider updating the folder structure to a more regular _node-like_ setup, with the index.html being the _landing_ file, a main.js containing the definition logic and an ```examples``` folder that could host more files in number and more elaborate uses? 

This is what I'm working on, as an example of how this could look: 
https://github.com/app-ui/component

Apart from being in line with Node, it'll also standardize importing to: 
```
<link rel="import" href="/bower_components/{{name}}">
```

Thanks again

**Comment by zenorocha** [comment]
The [new release](https://github.com/webcomponents/element-boilerplate/releases/tag/v1.1.0) leverages polyserve which should improve some paths issues.
