### ISSUE TITLE
Add some style

### ISSUE THREAD

**Issue by mohsen1** [webcomponents/element-boilerplate#9]

**Comment by zenorocha** [comment]
What for? The idea is to be as lean as possible.

**Comment by mohsen1** [comment]
Well, if it's a boilerplate it should guide user and for new comers it might be confusing where they should put their style.

**Comment by arthurvr** [comment]
> Well, if it's a boilerplate it should guide user and for new comers it might be confusing 

Guiding people isn't the point of a boilerplate.
